export const clearCommandId = 'draw.clear'
export const contextMenuId = 'draw.contextMenu'
export const duplicateCommandId = 'draw.duplicate'
export const exportMenuId = 'draw.exportMenu'
export const showCommandId = 'draw.show'
export const viewId = 'draw.views.whiteboard'
